### ISSUE TITLE
Avoid using stale access tokens in requests to Editor API

### ISSUE THREAD

**Issue by chrisroos** [RaspberryPiFoundation/editor-ui#1044]
We've been seeing quite a few [`Faraday::Unauthorized` errors reported by Sentry in Editor API](https://rpf.sentry.io/issues/5135885959/). These errors are being caused by stale access tokens being sent in the requests from the WebComponent.

I've narrowed the problem down to [this line in WebComponentLoader](https://github.com/RaspberryPiFoundation/editor-ui/blob/e3495a24ff296cf0c3c22910db25d02547c6dfd9/src/containers/WebComponentLoader.jsx#L58) which was introduced in [this commit by James M](https://github.com/RaspberryPiFoundation/editor-ui/commit/373b7162ae26d038cbbd1213a3f68db1f289b531). James's fix works in the case where the user stored in localstorage has an active (i.e. not expired) access token but causes failures if the access token has expired. I contemplated fixing this by checking the expiry date of the access token in `WebComponentLoader` but that doesn't feel quite right because that must already be happening somewhere else in the app (maybe in a library we're using for oidc)? Instead, I think it might be better if the `WebComponentLoader` only reads the user from state (and not from localstorage), and we rely on the component re-rendering when the user becomes available in the state. We know that the `WebComponentLoader` component renders (and therefore makes a request to editor-api with no `Authorization` header) before the user is available in state. This is fine for public projects (i.e. those where `user_id` is null) but fails for user projects (i.e. those where `user_id` is set). When the user becomes available in state I'd expect the component to re-render and make a request to editor-api with the `Authorization` header set correctly. At present, this second request doesn't happen because of [the condition in this line of `syncProject`](https://github.com/RaspberryPiFoundation/editor-ui/blob/e3495a24ff296cf0c3c22910db25d02547c6dfd9/src/redux/EditorSlice.js#L65).

**Comment by chrisroos** [comment]
I've been playing around with some ideas for this in PR #1043.

**Comment by chrisroos** [comment]
I wonder whether it might be worth going with the quicker fix for now, of not loading the user from localstorage if the access token has expired, as I think that might help reduce the errors we're seeing in production?

**Comment by floehopper** [comment]
As suggested by @chrisroos I've worked up the quick fix into https://github.com/RaspberryPiFoundation/editor-ui/pull/1046 to address this issue.

**Comment by floehopper** [comment]
After discussing this with @chrisroos & @sra405 this morning, we agreed to revert #1046, because it has been addressed by RaspberryPi/editor-api#337. It has highlighted some other potential issues which I've tried to detail in https://github.com/RaspberryPiFoundation/editor-ui/issues/1050. Moving this issue to "Ready to deploy", but maybe we want to close it...?
