### ISSUE TITLE
Set up custom events and test on Production

### ISSUE THREAD

**Issue by maddyjoe** [RaspberryPiFoundation/editor-ui#228]
So that we can gauge interactions with the Editor using quantitative methods, this ticket is to complete the work to set up basic **Plausible** and initial custom events.

Tasks:
- [x] add the code to the standalone Editor (expect we leave GTM for now cos Hotjar) --> but might need to split this ticket to merge that code up first and looks like we might want a staging and a prod version for testing reasons
- [ ] figure out a basic schema for anything that isn't out of the box analytics (assuming custom event stuff) and review it with Greg using this [working document](https://docs.google.com/spreadsheets/d/15kP1XxiJredeYvqNMCVgsgdmAVwJT9J8OuefCKVxJm8/edit#gid=0) as the basis and updating it to be relevant to how this is managed by Plausible
- [ ] test it! and once working knowledge share?
There is additional info from Greg around access creds and event documentation in the comments below (thanks Greg!)

**Comment by maddyjoe** [comment]
@grega do you have any sense of how we implement this with GA4/GTM - should it use IDs and class names given e.g. the names might get translated? hard to find a good balance between the names of things in the code, and the names of things in GTM when things might be subject to change?

**Comment by grega** [comment]
We're going to trial Plausible analytics here, as a replacement for Google Analytics (in short Plausible is; far simpler than GA, open source, lighter-weight, privacy-focused and doesn't require cookies thus allowing us to potentially remove cookie banners).

There's a staging instance set up here, which can be used to configure sites / snippets: https://staging-analytics.raspberrypi.org/sites (login details in LastPass).

There's no production instance just yet, that'll follow shortly.

Custom events are documented here: https://plausible.io/docs/custom-event-goals

**Comment by maddyjoe** [comment]
hey @grega I'm happy with how this has been set up in local. When you have time if you can have a quick look and help create a prod version of Plausible we can use to do set up in Prod that would be grand. No huge rush though

**Comment by grega** [comment]
@maddyjoe yep on it 👍 I have a PO open for Plausible hosted that will hopefully be sorted soon (am nudging the approvers today) and then we can get the prod set up finished...

**Comment by grega** [comment]
```
<script defer data-domain="editor.raspberrypi.org" src="https://plausible.io/js/script.js"></script>
```

Is the snippet for production.

And https://plausible.io/editor.raspberrypi.org is the dashboard (web@ log in is in LastPass).

**Comment by loiswells97** [comment]
Moving back to review as looks like I've already added the prod snippet
