### ISSUE TITLE
Add Hotjar to the standalone Editor

### ISSUE THREAD

**Issue by maddyjoe** [RaspberryPiFoundation/editor-ui#229]
As a RPF team member
I want to be able to see how young people are interacting with the new Editor
So that I can assess any areas of key user struggle, and look to fix forward as part of continual change/improvement

Tasks:

- [x] add the domain to the  RPF Hotjar account and submit a "add new domain" registration request so the domain can be upgraded to be on the non-profit free business plan
- [x] wait for Hotjar to process the request (should send an email confirmation to web@ email add with Maddy's name on it
- [x] engineers to [add the code snippet from Hotjar](https://www.hotjar.com/) and then once logged in using Web@ creds in Last pass, navigate to https://insights.hotjar.com/site/list and you'll see the domain for Editor and a prompt to "get install code"
In terms of which installation method Greg has recc'd that we use the "install via Google Tag Manager" as it gives us additional ability to turn it off fully/easily, without having to alter the Editor header code itself. 
Although Projects site has "installed via Header" as they don't use GTM on that Product, if you get stuck Lois, then Glen/Scott should be best placed to help

We can then let UXR team (Ale, Henna) know that should they want to add any explicit page URLs that sit under that domain and turn Hotjar on to e.g. sample session record interactions to gauge areas of user struggle.

**Comment by loiswells97** [comment]
Have added the Hotjar snippet through GTM and paused the tag to presumably stop it recording for now until we're ready to turn it on

**Comment by maddyjoe** [comment]
Yes definitely working--> Hotjar turns off capturing any numbers in the recording as standard e.g. in the input code, but we can turn this on AND specify URLs if we wanted it to be more targetted. Only thing that didn't seem to capture in the recording was the visual output for some reason.
Lois has turned it off in GTM, and I've turned it off in Hotjar for now.
Marking as completed.
