### ISSUE TITLE
Change code wrapping to scrollbar

### ISSUE THREAD

**Issue by maddyjoe** [RaspberryPiFoundation/editor-ui#240]
As a young person who is writing code
I want to be able to experiment with the code I write
And be able to easily see and edit my lines of code, including long lines

Following feedback from both ILT and Astro Pi teams, it sounds like for the scenario where young people are writing long lines of code we expect, or in the case of Astro Pi, have had feedback, that the wrapping behaviour for longer lines of code is confusing, esp. when it comes to being able to see the indentation/whitespace.

This issue is to:

- [ ] look at moving to implementing scrollbars when the code exceeds the available space in the input panel
- [ ] test that it works across browsers/OS (I think Chrome/FF have a diff way of getting a horizontal scrollbar to appear, with one defaulting it, and one needing us to be explicit that we want it to scrollbar)

There is the possibility that some of this could also be mitigated in the future with additional design I expect e.g. if the left hand panel and output/console were optionally collapsible it would give the young person more space in input before scrollbars are needed...

**Comment by tracygardner** [comment]
I agree with the wrapping issue causing confusing especially in combination with indentation markers.

Hmm, the cognitive load is really high if you can't see the whole line at the same time. Horizontal scrollbars are also quite tricky to use (vertical is fine if you have a scrollwheel but that's asking a lot in schools!) and far away from where you are coding (you may be able to use arrow keys if the scroll bar is selected but kids won't know that.)

Could we consider re-formatting such lines into multi-line statements as a strategy to use before resorting to scrollbars. It would be good to have multiline comment/uncomment to go with this though as it's a pain to have to do this for each line. 

    rect(x_coord, y_coord, w, h, top_left, top_right, # You can just add a newline here in Python
         bottom_right, bottom_left);

print("This is a really long line of code with lots of \ # You need to add a \ at the end of the line to add a newline here
characters")

Long lines happen quite a lot, especially once you are in a nested scope. 

PEP 8 suggests lines should be limited to 79 characters. This would be pretty high for the web and for younger readers. I'm fitting about 55 with the default font in our editor, I wouldn't want lines much longer than this.

On mobile, scrolling may be less of an issue as it's a native gesture and faster (but vertical scrolling may still be preferred.)

User testing needed!

**Comment by maddyjoe** [comment]
yes @tracygardner  so I think this change = an improvement but next steps = user test, get feedback, and plan in Design item to look at how we can help YP "easily author code" - given that might entail additional problem solving solutions like "full screen the input panel" option or "allow me to customise the space of each part of the editor" or something (obv ensuring that we are considerate with accessibility too!)
