### ISSUE TITLE
Check silent renew

### ISSUE THREAD

**Issue by maddyjoe** [RaspberryPiFoundation/editor-ui#281]
check if silent renew is set up and if so what expiry timescales it has on it i.e. likely ppl might want to be doing a thing for longer than 1 hour -->auto-refresh token

**Comment by maddyjoe** [comment]
When investigating this @sHtev has said:
// we don’t save session in hydra, just in profile, so normally you just redirect to /login on profile and pick up the session token, but silent renew expects hydra to have the session stored, it does not know how to redirect or get a login prompt, hydra just says “I don’t have a session, please log in” and the OIDC client basically just goes :shrug:
so we either 

1. work around sessions expiring and not lose state
2. or we talk about getting hydra to mirror profile session handling (aka ask Core if it's in their backlog)
3. we can increase the access token TTL to match profile session length which currently defaults to 1 hour (https://raspberrypifoundation.slack.com/archives/C02D2T8JMQU/p1670607176670669)//

Expect that the next steps is for Maddy/Patrick to check with Greg if we do something interim, but ideally/longterm my view = this should be standardised/fixed in Hydra by sounds of things, given speaking to Projects site people this is also an issue currently for Project site session expiry, not just Editor.
Front-end I'd expect the desired user behaviour is it boots them after 1 hr of actual idleness or a max time of 24 hrs or something.

**Comment by maddyjoe** [comment]
@grega 's steer (TY!) = this should get handled in the specific product application aka we call Hydra and ask for a new token. This = how it works for Projects site.
@patch0 please let me know your thoughts when you can --> and can then raise a backlog issue for us to make a change (ideally based on not-idle? --> fetch new token) at a later date.

**Comment by grega** [comment]
I believe Hydra v1 is handling sessions (and stores session data in the table `hydra_oauth2_access`). Haven't spent any time looking at this recently however so will refresh (ha) my memory...

As mentioned in the [Slack thread](https://raspberrypifoundation.slack.com/archives/C02D2T8JMQU/p1671102217628959), the `refresh_token` grant type will need adding to the Editor's Hydra client config.

**Comment by sHtev** [comment]
Further testing confirms silent renew works iff:

1) Client has `refresh_token` grant type as above
2) Identity provider (profile) sets `remember` and `remember_for` on both `acceptLoginRequest` and `acceptConsentRequest` API calls (so that hydra saves authentication success in its session data)

Token TTL can be set on a per-client basis - see https://www.ory.sh/docs/hydra/guides/client-token-expiration#lifespan-configuration-for-specific-clients
