### ISSUE TITLE
UI pagination component

### ISSUE THREAD

**Issue by IzzySmillie** [RaspberryPiFoundation/editor-ui#311]
**Outline**
Story: https://github.com/RaspberryPiFoundation/digital-editor/issues/47
Designs: [Light mode](https://www.figma.com/file/2PjcTUsL1rHl1IaAht8yTm/Python-Editor---Dev-Handover?node-id=458%3A15556&t=pzhq5QrPmQZUVde8-0) and [Dark mode](https://www.figma.com/file/2PjcTUsL1rHl1IaAht8yTm/Python-Editor---Dev-Handover?node-id=458%3A27070&t=pzhq5QrPmQZUVde8-0)

**ACs**
- [ ] Add the UI pagination component
- [ ] Make sure it is responsive and browser tested
- [ ] Track current page and last page to pass through to the API

**Comment by loiswells97** [comment]
What's left to do:
- Discussion around structure - should the pages be on different URLs with the page number in the query string, or should the pages be loaded from within the table component using `useEffect` with the current page number in the store?
- Fix problem where if you delete the only project on a page it should take you to the last page that has projects on (could possibly be easier to fix if we followed the second approach above as no need to trigger a redirect, just reload the projects from the API)
- Make the pagination component not show when there is only one page
- Think about whether we need all the link data we are getting from the API given the request structure we are using with redux, axios etc. or whether we should be doing it differently to make direct use of this information
