### ISSUE TITLE
Fix release apps

### ISSUE THREAD

**Issue by loiswells97** [RaspberryPiFoundation/editor-ui#352]
- Set `REACT_APP_BASE_URL` to `''` for the latest version, and `/releases/<tag-name>` for all other tagged releases
- Find a way of fixing login for release apps so it doesn't redirect you back to `editor.raspberrypi.org` when you log in

**Comment by patch0** [comment]
We're not expecting people to go to editor.raspberrypi.org/releases/vX.Y.Z, so I don't this is a problem we'll see (just yet).  So let's park this for now.
