### ISSUE TITLE
Test py5 imported mode

### ISSUE THREAD

**Issue by loiswells97** [RaspberryPiFoundation/editor-ui#392]
Check project code for py5 imported mode is working in both the editor and thonny and make any necessary fixes

**Comment by chrisruk** [comment]
I've been going through each of the main examples in https://github.com/RaspberryPiFoundation/editor-api/tree/65c1b13eecd9643f4a2956c259c62e4265c0d75a/lib/tasks/project_components and removing `py5.` and adding `# Py5: imported mode` at the start.

target_practice_example/main.py - ok
rocket_launch_example/main.py - ok
powerful_patterns_yakan_weaving_example/main.py - ok
powerful_patterns_spirals_example/main.py - ok
powerful_patterns_random_faces_example/main.py - ok
powerful_patterns_mcewen_tartan_example/main.py - ok
powerful_patterns_kek_lepis_sarawak/main.py - ok
powerful_patterns_art_deco_wallpaper_example/main.py  - ok
make_a_face_tribal_mask_example/main.py - ok
make_a_face_stacked_faces_example/main.py - ok 
make_a_face_kawaii_fruit_example/main.py - ok
make_a_face_interactive_example/main.py - ok
make_a_face_animated_example/main.py  - ok
dont_collide_skiing_cat_example/main.py - can't see the skiing cat, but can see trees
dont_collide_dont_pop_example/main.py - can't see balloon, can see cacti
dont_collide_dodge_asteroids_example/main.py - can't see rocket, can see moons
dont_collide_clean_car_example/main.py - ok
dont_collide_avoid_germs_example/main.py  - couldn't see players character

**Comment by maddyjoe** [comment]
Just so we don't lose it AND can remember to close it when no longer needed for testing - the original PR/Issue for "Draft updates to use py5 in first python path" is this badger https://github.com/RaspberryPiFoundation/editor-api/issues/118
