### ISSUE TITLE
Spike: Responsive HTML output panel for the editor

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#428]
How do we best support multiple output screen sizes on the users device?
Do we scale the output to fit the output panel?
Do we add an additional scroll and keep the output 1:1?
How do these options impact the input panels and available screen space?

Widths to play with:
375px, 768px, 1600px, 1920px

**Comment by sra405** [comment]
@maxelkins can you give us rough screen sizes to play with

**Comment by magdalenajadach** [comment]
Issues:

1. Incosinstent use of .css/.scss files htmlrunner.css

**Comment by magdalenajadach** [comment]
![Image](https://user-images.githubusercontent.com/8046557/232016309-49e766a3-f9a5-42e9-86c3-914600804978.png)

**Comment by sra405** [comment]
You ok pushing your branch @magdalenajadach and I can take a nosey 😄
