### ISSUE TITLE
Spike: Multiple input panels for the editor

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#431]
Consider dragging tabs between panels
Keyboard accessibility (research on current approaches)

Current WIP designs:
https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=1900-118677&t=xsD5IbunV7NXBj2p-4

**Comment by sra405** [comment]
@max to link design

**Comment by loiswells97** [comment]
## What's changed in the spike (#438)

- Create custom `DroppableTabList` and `DraggableTab` to incorporate drag and drop functionality into existing tab structure
- Update `openFiles` to be a list of lists, with one list of open files for each file panel
- Update `focussedFileIndex` to be a list of indices of open files, one for each file panel, and rename to `focussedFileIndices`
- Slight refactor to tab opening/closing/focussing etc. to reflect this

## What's left to do after spike

- Look into and fix keyboard interactions of switching between tabs versus selecting a tab to drag/drop (looks like switching between tabs is currently broken)
- Create content for empty (newly-opened) file panel as per designs, and think about what should happen when you close the last tab in a file panel (should it be empty or close the panel?)
- Think about whether files should always open in the top panel
- Option to switch between panels being rows/columns
- Dropdown menu with 'new panel' and row/column switching options
- Limit number of open panels to 3
- Fix broken tests
