### ISSUE TITLE
Input/output responsiveness

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#467]
[design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=2044-124009&t=ougreTAon5gI465F-4)

**Comment by sra405** [comment]
think of panel resizing too

**Comment by maxelkins** [comment]
## Details

At the given breakpoint the input and output panel should stack, this makes the editor much easier to use on smaller screen sizes where we have more vertical space than horizontal space.
