### ISSUE TITLE
Sidebar component

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#480]
HTML/CSS v2 https://github.com/RaspberryPiFoundation/editor-ui/issues/538

Update Sidebar component based off updated designs.

Has a link to the ProjectBar due to functionality moving between the two.

[design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=2044-119838&t=ougreTAon5gI465F-4)

**Comment by sra405** [comment]
Note: review and move resize component

**Comment by magdalenajadach** [comment]
https://staging-editor.raspberrypi.org/branches/issues_480_Sidebar_component/en/

**Comment by sra405** [comment]
merged up
