### ISSUE TITLE
Sidebar - images

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#496]
As a user
I want to access images in the sidebar/menu
So that I can navigate to all the files in my projects

-------------
[Design link](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1118-13773&mode=dev)

**ACs**
- [ ] I can see all the available image files for my **projects site** project
- [ ] Images cannot be used in blank projects, so the button should be hidden on these
- [ ] Double-check image sizes to make sure they are not too big (review and confirm with Max during development to see how it looks and resizes)

**Comment by sra405** [comment]
Hide tab if theres no images in project

**Comment by sra405** [comment]
@magdalenajadach to refine

**Comment by magdalenajadach** [comment]
[Take a look at the notes from Max](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1150-13119&mode=dev)

**Comment by loiswells97** [comment]
Note that there is an existing `ProjectImages` component that was used in the old sidebar that might be able to be tweaked and reused here

**Comment by sra405** [comment]
closed with latest merge
