### ISSUE TITLE
Output into own window - HTML/CSS

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#498]
HTML/CSS Post MVP (https://github.com/RaspberryPiFoundation/editor-ui/issues/493)

[design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=1900-118972&t=EzMwlXdPyjPPMgOU-4)

**Comment by sra405** [comment]
Not sure if this is in/out of scope for the editor - need to consider use case

**Comment by maxelkins** [comment]
Issues:

- ‘New tab preview’ not getting updates without refreshing the page / running.
- What file to run when you click run in the ‘new tab preview’
- Currently ‘new tab preview’ defaults to index.html
- Navigating back pages in the ‘new tab preview’

MVP:

- ‘New tab preview’ should show the html file that is currently being previewed in the editor.
- Users can still navigate with in-page links
- Users need to be able to navigate back in the preview - using native browser back/forwards buttons

**Comment by sra405** [comment]
closed with merge of #536
