### ISSUE TITLE
Sidebar - files

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#509]
As a user
I want to access files in the sidebar/menu
So that I can navigate to all the files in my projects

-------------

Notes
[Link to the main component](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=2044-119866&mode=dev)

**ACs**
- [x] I can see all the files related to the project in the view

**Comment by sra405** [comment]
@magdalenajadach to refine

**Comment by magdalenajadach** [comment]
[Link to the main component ](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=2044-119866&mode=dev)

Most likely we already have everything, check out Icons.js to check if all the assets are there

**Comment by PetarSimonovic** [comment]
As Magda comments above, we have everything to satisfy acceptance criteria for the ticket. However, there was a small issue: pressing "Enter" when adding a new , valid file should  close the "Add file" modal, but it stays open:

**Comment by sra405** [comment]
closed as part of https://github.com/RaspberryPiFoundation/editor-ui/issues/480
