### ISSUE TITLE
Axe accessibility audit

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#518]

**Comment by magdalenajadach** [comment]
https://raspberrypifoundation.slack.com/archives/C02JBAA2NFP/p1684839980905159

- the root page (which is more or less the same as the page showing a specific project), 
- the embedded viewer and the projects index. 
- Apart from that it might be worth checking the project page and embedded viewer in different states e.g. when a particular library is used such as the example projects from the intro to python path

**Comment by magdalenajadach** [comment]
## Critical issues

### 1. Root page https://editor.raspberrypi.org/en/
a. Certain ARIA roles must contain particular children
Ensures elements with an ARIA role that require child roles contain them
Element Location:
`.editor-input > .react-tabs[data-rttabs="true"] > .react-tabs__tab-container > ul
<ul class="react-tabs__tab-list" role="tablist">`

<img width="1128" alt="Screenshot 2023-05-26 at 11 14 56" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/8046557/550df10d-16d4-4fb0-bb2c-53aea5ee09ec">

b. Certain ARIA roles must be contained by particular parents
Ensures elements with an ARIA role that require parent roles are contained by them

Element Location:
#react-tabs-0
`<li class="react-tabs__tab react-tabs__tab--selected" role="tab" id="react-tabs-0" aria-selected="true" aria-disabled="false" aria-controls="react-tabs-1" tabindex="0" data-rttab="true"><span class="react-tabs__tab-inner">main.py</span></li>`

<img width="1110" alt="Screenshot 2023-05-26 at 11 17 28" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/8046557/b84b5a4f-5120-4899-b202-ba9297e03f92">

**Comment by magdalenajadach** [comment]
### 2. List of projects page https://editor.raspberrypi.org/en/projects
No critical issues

### 3. A single project
a.  Buttons must have discernible text
Ensures buttons have discernible text
Element Location:
`.theme-btn__icon--light
<button class="theme-btn__icon theme-btn__icon--light theme-btn__icon--active">`
<img width="1342" alt="Screenshot 2023-05-26 at 11 22 03" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/8046557/260a1ee1-6a22-4d5e-95ca-523ca4be27c8">

**Comment by magdalenajadach** [comment]
4. Embedded project https://editor.raspberrypi.org/en/projects/hello-world-starter 
No new issues that they would be different then those two recorded for the starter page

**Comment by sra405** [comment]
Tickets added for the root and projects issues found 👍
