### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#531]
HTML/CSS v1 (https://github.com/RaspberryPiFoundation/editor-ui/issues/493)

Essentially the python and html/css buttons should take the user to "boilerplate" projects with main.py and index.html in respectively so they can remix those projects e.g. our [blank html starter project](https://editor.raspberrypi.org/en/projects/blank-html-starter).

The current root doesn't need to exist as far as I'm aware.

[design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=1911-118520&t=ipW1q68iWkllhJsw-4)

**Comment by magdalenajadach** [comment]
Consider refactoring the button component to use the link. Here is the Slack conversation about the workaround https://raspberrypifoundation.slack.com/archives/C02JBAA2NFP/p1686576981943209
