### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#568]
As a user, I want to use a navigation that works on my mobile or tablet device, so that I can use the editor on my preferred device.

[Design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3009-79462&mode=design&t=aI6RVte6GXwvodaO-4)

------

**General ACs for mobile**
- Account navigation follows whatever is the latest (out of scope for specific mobile support)
- Make sure the breakpoints are at the same width of the application
- Users cannot zoom in/out by pinching (since we have text resizing in the settings)
  - **Tech question:** Is this enabled by default, or something we have to disable? 
- ~~Auto-run/refresh is disabled on mobile.~~ We have not implemented this functionality.

**Story ACs**
- Mobile nav follows the designs - use 'Output' for Python and 'Preview' for HTML/CSS
- Mobile nav appears at the correct breakpoints
- Make sure the breakpoints are at the same width of the application

**Comment by magdalenajadach** [comment]
Output - for the Python, Preview - for the html

**Comment by sra405** [comment]
closed with merge. Design review tickets created
