### ISSUE TITLE
Mobile sidebar

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#571]
As a user, I want to navigate the editor on my mobile, so that I can see my project details and amend settings on my preferred device.

[Design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3009-79465&mode=design&t=aI6RVte6GXwvodaO-4)

**Design queries**

1. ~~Should we have the account nav at the top when sidebar is open?~~
2. ~~Should 'Projects' be 'Project details'?~~
3. ~~Should the save button be included on 'Projects' sidebar tab across all viewport sizes?~~

------

**General ACs for mobile**
- Account navigation follows whatever is the latest (out of scope for specific mobile support)
- Account navigation is always visible on any viewport
- Make sure the breakpoints are at the same width of the application
- Users cannot zoom in/out by pinching (since we have text resizing in the settings)
  - **Tech question:** Is this enabled by default, or something we have to disable? 
- ~~Auto-run/refresh is disabled on mobile.~~ We have not implemented this functionality.

**Story ACs**
- Mobile sidebar follows the design tweaks
- Mobile sidebar appears at the correct breakpoints
- Sidebar opens on the 'Project details' view by default - let's update to 'Project details' **across all viewports**
- Save button is included on 'Project details' sidebar tab **across all viewports**

**Comment by maxelkins** [comment]
> Should we have the account nav at the top when sidebar is open?
Yes - current pattern is that account nav is always visible.

> Should 'Projects' be 'Project details'?
I'm still not 100% on the name but I think 'Project details' works better. So yes.

> Should the save button be included on 'Projects' sidebar tab across all viewport sizes?
I cant see any downside to having it at all sizes.

**Comment by danhalson** [comment]
After discussions with @loiswells97 we think this is the work left on the PR:

1. Dimension of Project Files tab content
2. Width of menu button
3. Potential bug when hiding buttons (tabs) on mobile width as # of tabs should match number of TabPanels
4. Close button doesn't fully work and is in the wrong position
5. Should return to previous tab when closing menu
6. Shouldn't close tab on second click from menu bar
7. Bug in SaveStatus when clicking home from menu bar (see DevTools)
8. Vertical resize should move elements in menu bar to fit available space
9. Run button looks smaller, is that correct?
10. MobileSidebarBar isn’t DRY, and should maybe be folded into SidebarBar with isMobile clause
11. Test coverage and failures

I think the work pivots on whether we think it's best to proceed with the approach of the menu being a tab, or implementing it as an independent button that sits in the tab options. Worth considering that Issues 2 through 5 could be avoided by implementing a button for the menu, and would mean we're not bending the tab component to do something it isn't really designed to do, but would require a small amount of refactoring.

**Comment by sra405** [comment]
closing as merged and sidebar design review completed [here](https://github.com/RaspberryPiFoundation/editor-ui/issues/624)
