### ISSUE TITLE
Mobile general notes

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#587]
As a user, I want a code editor that works on my mobile or tablet device, so that I can use the editor on my preferred device.

[Designs]()

------
This story covers general ACs for mobile implementation.

**ACs**
Account navigation follows whatever is the latest (out of scope for specific mobile support)
Make sure the breakpoints are at the same width of the application
~~Users cannot zoom in/out by pinching (since we have text resizing in the settings)~~
~~Tech question: Is this enabled by default, or something we have to disable?~~
~~Design question: Should we keep the standard mobile behaviour for pinching, for accessibility and user expected behaviour?~~
~~Auto-run/refresh is disabled on mobile. We have not implemented yet.~~

**Comment by sra405** [comment]
Nav hasn't been touched and breakpoints has been highlighted in the design review so closing as a result
