### ISSUE TITLE
Create goals for starting and downloading projects

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#606]
As a PM, 
I want to track the number of editor visitors who have 1) started a HTML/CSS and/or Python project and 2) downloaded a project
So that I can better understand core usage

ACs
Implement 3 custom event goals in Plausible
- ‘Start coding Python’ button clicks (homepage)
- 'Start coding HTML/CSS’ button clicks (homepage)
- 'Download' button clicks

**Comment by sra405** [comment]
well `create-issue-branch[bot]` that's new and completely useless... thanks

**Comment by danhalson** [comment]
Not sure why this isn't linking, but here's the PR: https://github.com/RaspberryPiFoundation/editor-ui/pull/607
