### ISSUE TITLE
Editor - Mobile support: Sidebar save

### ISSUE THREAD

**Issue by PetarSimonovic** [RaspberryPiFoundation/editor-ui#626]
Sidebar - Save
- [x] - Save button should be full width and secondary style
- [ ] - Save status icon should be 1.5x1.5rem
- [x] - Save status text should be 1rem
- [ ] - Note save status style is different in sidebar to the save status style when side bar is close.

Design:
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/8718ab83-62f2-4af4-904f-e13bfcb5c6a9)
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/674f544e-1acd-4365-b6c7-56fa671d352f)

**Comment by PetarSimonovic** [comment]
Task taken from #624

**Comment by maxelkins** [comment]
## Review

- [ ] In firefox the button doesn't fill.
`width: -webkit-fill-available;` doesnt work in firefox.
Suggestion: `display: flex` on `projects-panel__save`, and `width: 100%` on button. Seems to work in all browsers, but worth double checking.
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/58e68d4a-aace-40d5-9735-407edf54bb05)

- [ ] In dark mode top border is wrong color. Should be `rpf-grey-600`
- [ ] In dark mode hover state is broken. See [designs](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=934-8743&mode=design&t=bWjGLXNdElCxK4Yp-4)
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/9034f5d0-2b55-401a-86dc-30d3160c4bd8)

- [ ] My mistake before, the text should be 1.25rem. Which should be what the design system button is set to by default, so shouldnt need to override the size.

**Comment by sra405** [comment]
Remaining items separated out into https://github.com/RaspberryPiFoundation/editor-ui/issues/636
