### ISSUE TITLE
Editor - Mobile support: dynamic viewport height

### ISSUE THREAD

**Issue by PetarSimonovic** [RaspberryPiFoundation/editor-ui#627]
Need to use [dynamic viewport height](https://web.dev/viewport-units/)  so that on mobile the editor size accounts for the browser app UI (address bar etc.)
At the moment the overflow on mobile meaning parts of the editor UI are hidden.

**Comment by PetarSimonovic** [comment]
Need to use [dynamic viewport height](https://web.dev/viewport-units/) 100dvh so that on mobile the editor size accounts for the browser app UI (address bar etc.)
At the moment the overflow on mobile meaning parts of the editor UI are hidden.

**Comment by maxelkins** [comment]
# Review

Tested on android firefox and chrome.

Working well when in the editor!

Only issue I found was on the landing page and projects page. You can scroll to see the whole page but, when you scroll all the way to the end, you then have to stop scrolling, then scroll again to reveal the very bottom of the page. This is the same for the top when scrolling back up. I think it seems like the amount you have to 'rescroll' is equal to the address bar height, I might be wrong on this. I'm not sure if this is 'normal' but I've never noticed that on other sites.

Video:

If you watch the 'cusor' (my finger) You'll see I'm scrolling down then I have to stop scrolling and scroll again to see the bottom (top if scrolling up). Same issue in chrome too.


https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/359c64d6-9108-46a0-bc87-83066f07d612

**Comment by sra405** [comment]
Bug raised [here](https://github.com/RaspberryPiFoundation/editor-ui/issues/637) and added to next sprint so closes this ticket
