### ISSUE TITLE
Editor - Mobile support: navigation tabs

### ISSUE THREAD

**Issue by PetarSimonovic** [RaspberryPiFoundation/editor-ui#629]
## Issues
- On both the navigation tabs (fig.1) and the open file tabs (fig.2) the border + background colour do not meet the contrast requirements for "Graphical Objects and User Interface Components"
  - This is particularly an issue with the navigation tabs, or when multiple file tabs are open as the border is the only signifier of what is selected.
-  On light mode the nonselected navigation tab is styled differently to dark mode. i.e. doesn't have a background. (fig3).

## Solution

These issues are solved with the new design and colours of the [file tabs](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1144-10198&mode=design), and [navigation tabs](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1622-15973&mode=design&t=8eq0MOzXLMvk4a5O-4).

If building the tabs to the new design is not in scope then the current colours should be updated to meet the "Graphical Objects and User Interface Components" contrast requirements. Suggestion for this below:

### Dark mode
- [x] Selected outline --> rpf-teal-400
- [x] Selected background --> rpf-grey-600
- [x] Unselected background --> rpf-grey-600

### Light mode
- [x] Selected outline --> rpf-teal-900
- [x] Selected background --> rpf-grey-50
- [x] Unselected background --> rpf-grey-50

---

fig1:

![Image](https://user-images.githubusercontent.com/43481548/261319024-5d65ac2e-9a05-4552-bf15-2dd8cdcec9a6.png)

fig2:

![Image](https://user-images.githubusercontent.com/43481548/261319069-b406af31-1676-4527-80b2-0f39ab026174.png)

fig3:

![Image](https://user-images.githubusercontent.com/43481548/261319434-60b243f3-3458-434c-a5d5-07d41b509a05.png)

Design:

![Image](https://user-images.githubusercontent.com/43481548/261319617-6d2af75b-596a-491b-986c-0f567a0f6ed5.png)

![Image](https://user-images.githubusercontent.com/43481548/261319779-a572b31f-c000-4061-9a8e-030eedea233c.png)

**Comment by PetarSimonovic** [comment]
Task taken from #624

**Comment by sra405** [comment]
Can we sort this out as part of this ticket too? https://raspberrypifoundation.slack.com/archives/C02JBAA2NFP/p1693581742150969?thread_ts=1693568755.068239&cid=C02JBAA2NFP

**Comment by magdalenajadach** [comment]
I believe it was fixed by @PetarSimonovic which his PR - according to the Slack discussion above.

**Comment by maxelkins** [comment]
- [ ] In dark mode correct border colour only shows when the tab is clicked

Before click (incorrect):
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/df4fb7d5-c339-4e17-9053-ba80edee8ec1)

After click (correct):
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/116b4839-e7c6-41b7-89f1-8d9e315a042c)

**Comment by magdalenajadach** [comment]
PR: https://github.com/RaspberryPiFoundation/editor-ui/pull/635

**Comment by sra405** [comment]
closed with merge
