### ISSUE TITLE
Tech discovery/planning: ADR prep for Editor-Projects integration

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#640]
Design documentation: https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3655-9504&mode=design&t=Ez5YV8GFypuQ2v5y-0

**Comment by sra405** [comment]
Initial spike - https://github.com/RaspberryPiFoundation/editor-ui/pull/651/files

**Comment by sra405** [comment]
Initial tech discussion and potential blockers to explore [here](https://www.figma.com/file/ASiMsS3z5yoIFDtdIwBwh3/Editor-Integration-Brainstorm?type=whiteboard&node-id=0%3A1&t=4qOHyOqUpeYvC3Fz-1)

**Comment by sra405** [comment]
merge draft ADR
