### ISSUE TITLE
Fix dark mode save button on tablet

### ISSUE THREAD

**Issue by loiswells97** [RaspberryPiFoundation/editor-ui#647]
<img width="252" alt="Screenshot 2023-09-14 at 12 53 04" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/88904316/b84ff971-4b11-40e8-9e98-eaedb09931cc">

**Comment by sra405** [comment]
fixed by https://github.com/RaspberryPiFoundation/editor-ui/issues/636
