### ISSUE TITLE
Discuss: Content integration approaches and ideals

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#654]
This is a placeholder for a discussion and brief docs on how we want our content to interact with the editor, points of note include:

- How do the steps of the project work with the editor?
- Do we prevent users from moving on until they have completed a step properly?
- How can we guide them effectively?
- Does each project step have a starter code editor project? And do we wipe the users code when they go to the next step?
- What if a user diverges from the project content and wants to start again?

This will inform how the instructions interacts with the user input panel (if at all).

**Comment by MFarringtonRPF** [comment]
Discussion summary: 
- Instructions and input are separate. The only instance of injecting code into input is on Step 1, where we inject the starter code. 
- We're happy to drop 'step X' from the URLs given there is no technical implications e.g. on progress tracking
- We should introduce a 'Start project over' button, which takes users back to Step 1 and the input panel is reset to show the starter code. The location of this button is TBC - likely on the 'beta slice' on the project page and somewhere within the integrated view - @maxelkins to consider.

**Comment by sra405** [comment]
- Project site instruction steps and and the user code input panel will be separate for this MVP
- Users will be able to toggle between instruction steps when they see fit but there's no need to surface the step number in the URL like we currently do in the old school instructions so my current thinking is we have a `/editor` path and start new users at the start and put existing users at the right step (as saved in projects-admins progress table) with their code retrieved.
- We don't guide them but allow them to go and do at their own pace
- Each project site project will have 1 code editor starter code projects (1-to-1) so when a new user starts an integrated project the starter code is loaded and remixed. Code is not wiped between steps.
- A restart or reset button is being considered but currently no mechanism for starting again
