### ISSUE TITLE
Discovery: Persisting web component users code

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#657]
As part of an integration the need to reload existing users code is essential.

Use case: A user returns or reloads a page of the project site with an editor integration they've partially completed.

Things to consider:
- Local storage for the web components? - similar to the standalone editor
- Storing anonymous users code via the API? - could have implications with safeguarding due to free text fields in the editor and no association to a user?
- Utilising the remix functionality in the API? - auto save changes to the base project code against the user and/or session
- Using a user/session ID attribute in the web component tag? - enables a lookup to be performed but would need to ensure security so it couldn't be used to load anyones projects

**Comment by sra405** [comment]
User auth prototypes could force us into bumping project site hydra to v1 (https://github.com/RaspberryPiFoundation/projects-ui/issues/2085)

**Comment by loiswells97** [comment]
After initial investigations:
- Can move `localStorage` and saving logic into its own hook with some modification and reuse in the `WebComponentLoader`, meaning that the web component can save things!
- Gave the web component `identifier` and `accessToken` attributes (for now), so you can load up public projects from the API as well as private ones, provided you give a valid access token (at the moment this is working with tokens from the editor site, but need to work out whether we need to upgrade to Hydra v1 to use tokens from projects site or whether v0 tokens will suffice)
- Adding a save button into the web component - as long as you provide valid credentials (how to do this securely in projects site?), you can save your work 🎉 
- As a side note, also discovered that all components to be used in the web component need the `import React from 'react'` line at the top to render

**Comment by loiswells97** [comment]
Is storing anonymous users' code worthwhile? We have their code in localStorage already and either way the project will be orphaned at the end of the session
