### ISSUE TITLE
Fix web component v0.15.0+ for use in MZ

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#658]
Currently all versions of the web component beyond v0.14.0 don't show the sense HAT model when integrated into the [Mission Zero site](https://missions.astro-pi.org/mz/code_submissions/new).

An investigation and fix into the issue is needed. It is suspected that a Content Security Policy violation for Draco WASM is causing the issue:

```shell
Refused to connect to 'https://www.gstatic.com/draco/versioned/decoders/1.5.5/draco_wasm_wrapper.js' because it violates the following Content Security Policy directive: "connect-src 'self' https://www.google-analytics.com https://stats.g.doubleclick.net https://astro-pi-submitted-code-production.s3.eu-west-2.amazonaws.com https://editor.raspberrypi.org".
```

![Image](https://user-images.githubusercontent.com/74183390/268991747-c00bfad1-dbd7-4c85-b278-9e70e43e56ac.png)

**Comment by PetarSimonovic** [comment]
The `refuse to connect` issue appears on all versions of the editor, alongside a `429 (Too Many Requests)` error, yet neither prevent the HAT model from loading.

After version 14, an `Uncaught (in promise) TypeError: Failed to fetch` also crops up, which seems to be causing the issue with the HAT

**Comment by sra405** [comment]
Currently on a tablet sized screen the sense HAT model is too small to see and needs a min height

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/08051264-ad0b-4ad7-90af-97f0d8141c16)
