### ISSUE TITLE
Discovery: Investigate potential monitoring approaches

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#660]
Investigate potential solutions to error monitoring. With the current assumption that the web component will be utilised for integrating the editor into other products we'll need to determine how best to track:
- If the web component is readily available
- If the web component is behaving as expected (potentially covered with testing prior to release)
- If a specific integration is failing (causing error codes and/or failing to render for the user)

**Comment by magdalenajadach** [comment]
Make sure to monitor the Web Component separately to avoid mistakes when flagging up

Review the tools we have already - check out Slack integrations
- [#digital-alerts](https://app.slack.com/huddle/T0650R0NQ/C1CTUF198) Slack channel - monitors Heroku and Pingdom
-[ #digital-notifications](https://app.slack.com/huddle/T0650R0NQ/C48ASP97C) Slack channel - monitors Sentry and Contentful

**Comment by magdalenajadach** [comment]
Apps we currently use:
1. Pingdom
- app up/down (uptime measures)
2. Heroku Stats
3. Sentry

**Comment by sra405** [comment]
It'd be great if you could explore expanding the build alerts. The whole code editor build process is new to me but if we could channel alerts to these channels that'd be great!

> Make sure to monitor the Web Component separately to avoid mistakes when flagging up
> 
> Review the tools we have already - check out Slack integrations
> 
> * [#digital-alerts](https://app.slack.com/huddle/T0650R0NQ/C1CTUF198) Slack channel - monitors Heroku and Pingdom
> * [ #digital-notifications](https://app.slack.com/huddle/T0650R0NQ/C48ASP97C) Slack channel - monitors Sentry and Contentful

**Comment by sra405** [comment]
What would be really interesting to know/find out is if we can monitor the web component. Not just if it's hosted on the domain it should be but if the current release is working. Greg mentioned we've got a BrowserStack account and we could look at automating some relatively complex checks 👀 

> Apps we currently use:
> 
> 1. Pingdom
> 
> * app up/down (uptime measures)
> 
> 2. Heroku Stats
> 3. Sentry

**Comment by magdalenajadach** [comment]
Within the Digital Products team we already have integrated a few tools. Two of them are the best use case for the Web Component - Pingdom and Sentry.

### Tools

Using Pingdom and Sentry together is a common practice. Pingdom is great for monitoring a website's availability and performance, and Sentry to tracking and resolving any errors or exceptions that occur in the application. 

1. Pingdom is primarily used for monitoring the uptime and performance of web applications. It regularly checks websites from multiple locations worldwide and alerts you if it's down or experiencing performance issues. It can also help with performance issues and flag up bottlenecks. 

Soon, we will be moving away from Pingdom to [Uptime](https://betterstack.com/docs/uptime/uptime-monitor/) which gives more insight into the content itself. 

2. Sentry is focused on tracking and monitoring errors and exceptions in software applications. It provides real-time alerts when errors occur. It captures detailed information about errors, including stack traces, environment information etc.

Both of them can be integrated with Slack, email, etc.


### Browserstack

BrowserStack is a cloud-based platform that allows to perform automated and manual testing of web applications across various browsers and devices. For now, we only use manual testing but we could take advantage of access to it. Detailed info, on [how to get started.](https://app-automate.browserstack.com/dashboard/v2/getting-started )

With the BrowserStack we can narrow down test cases we want to automate. It allows to specify the desired browser, device, OS, and other configurations - to ensure that tests are executed on the specific environments you need.

 For complex scenarios,  test scripts might perform actions like:
     - Interacting with multiple elements on a page
     - Handling pop-ups, alerts, and iframes
     - Implementing data-driven testing
     - Performing validations based on API responses
     - Implementing conditional logic within tests


BrowserStack can only be automated with CI/CD pipeline. This ensures that tests are executed automatically whenever there's a code change.


### To consider

1. Web component versioning 
Think about accessing the online version of the component. It would be nicer to have it as the latest version: 
`https://editor.raspberrypi.org/webcomponent/latest.js` to avoid keeping track of every release/update it. 

2. Sentry integration 
Load the Sentry within the web component itself to provide dynamic error reporting with the context.

Sentry has [.withScope function](ttps://docs.sentry.io/platforms/javascript/enriching-events/scopes/) that would be very useful with the tagging/context. 
```
Sentry.withScope((scope) => {
  scope.setTag('astro_pi', true); // Set a tag for your component
  scope.setContext('custom_context', {
    dynamicInfo: 'VALUE_HERE', // Add dynamic information
  });

  // Trigger an error (e.g., using throw new Error())
});
```

### Recommendation 
Implement Pingdom/Uptime along with Sentry to track different aspects of the application behavior. Follow up with BrowserStack integration to get the most out of automated testing.
