### ISSUE TITLE
Fix `p5` bug when mobile sidebar opened

### ISSUE THREAD

**Issue by loiswells97** [RaspberryPiFoundation/editor-ui#663]
If sidebar opened on mobile while `p5` sketch is running then when you close the sidebar the error in the first screenshot pops up. When you click `run` the error in the second screenshot pops up. When you click `run` again the sketch is running twice and you can only stop one of them 🤯 

![IMG_3321](https://github.com/RaspberryPiFoundation/editor-ui/assets/88904316/c9279966-872e-41cc-9b4a-d2b5cd72e5c8)
![IMG_3322](https://github.com/RaspberryPiFoundation/editor-ui/assets/88904316/f1d09f6a-4982-445d-bae3-b56fc4f9cda2)

**Comment by sra405** [comment]
closed with merge
