### ISSUE TITLE
Fix useEffect web component warnings

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#668]
We've had `useEffect` dependency warnings on the web component for some time. As we're now looking to update and expand the web component functionality it'd be best to address these before additional work is started.

It's worth:
- Reviewing the dependency array and seeing if they're needed
- Add them to the array or refactor into multiple useEffect hooks
- Test to ensure over rendering or infinite loops aren't introduced

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/013467ab-b82e-4b0a-897f-d12bc3e954df)

**Comment by magdalenajadach** [comment]
Take a look at this PR, possible fix for useEffect https://github.com/RaspberryPiFoundation/editor-ui/pull/595/files
