### ISSUE TITLE
Sense HAT LED need moving anti-clockwise

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#693]
As part of the Sense HAT library `set_pixel` allows the user to set individual pixels to various colours ([docs](https://pythonhosted.org/sense-hat/api/#:~:text=called%20set_pixels.-,set_pixel,-Sets%20an%20individual)). Currently the x, y coordinates documented aren't whats displayed.

- sense.set_pixel(0, 0, (255, 0, 0)) - should be top left
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/35c33289-4dd4-4108-a13b-78143bf6e337)

- sense.set_pixel(0, 7, (255, 0, 0)) - should be bottom left
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/9703a999-b46b-4ccc-9cfb-1894638f1c56)

- sense.set_pixel(7, 0, (255, 0, 0)) - should be top right
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/5d091793-49e1-4197-b27e-709ee1809ca1)

- sense.set_pixel(7, 0, (255, 0, 0)) - should be bottom right
![image](https://github.com/RaspberryPiFoundation/editor-ui/assets/74183390/f8010c6d-4d69-4e9a-b397-d748d6e29bcc)

Fix:

All are out by 90 degree anti-clockwise so the LED on the model needs adjusting accordingly

**Comment by loiswells97** [comment]
Looks like nothing needs to change on this one... The Astro Pi model has the SenseHat "portrait", whereas the `sense_hat` library assumes the SenseHat is "landscape", hence the `sense.set_rotation(270)` line in the Mission Zero starter project, which rotates the LED display to be in the orientation the user expects.

https://github.com/RaspberryPiFoundation/editor-ui/assets/88904316/7f7a938d-f801-4b33-aace-1ba2e1ac58dd

**Comment by sra405** [comment]
> Looks like nothing needs to change on this one... The Astro Pi model has the SenseHat "portrait", whereas the `sense_hat` library assumes the SenseHat is "landscape", hence the `sense.set_rotation(270)` line in the Mission Zero starter project, which rotates the LED display to be in the orientation the user expects.
> 
>  IMG_3364.MOV

fyi @alx-pi
