### ISSUE TITLE
Update and re-enable stylelint and fix errors

### ISSUE THREAD

**Issue by loiswells97** [RaspberryPiFoundation/editor-ui#694]
- [x] Update `stylelint` from version 10 to version 15
- [ ] Fix the `>100` `stylelint` errors
- [ ] Re-enable the `stylelint` check as part of CI (currently commented out in `.github/workflows/ci-cd.yml`)

**Comment by magdalenajadach** [comment]
We have a lot of errors, but they occur within 16 files

Grouped as follows:
1. Unexpected unknown unit "dvh"   unit-no-unknown (fixed already within this PR)
2. Unexpected duplicate - removed from three files

Rest of the rules to fix:
3.   Unexpected unknown property "container-type"   - property-no-unknown    
4. Unexpected unknown at-rule "@container" (at-rule-no-unknown)   scss/at-rule-no-unknown
5. Expected selector "." to come before selector "." no-descending-specificity - most errors

**Comment by magdalenajadach** [comment]
https://www.npmjs.com/package/optimize-css-assets-webpack-plugin - webpack + 5 upate

**Comment by magdalenajadach** [comment]
Fixed a few linting errors:
1. Duplicates
2. Support for 'dvh' unit

Pausing it when we merge [Webpacker issue](https://github.com/RaspberryPiFoundation/digital-editor/issues/38) (I would need to update it here as well, merge conflict alert)

**Comment by magdalenajadach** [comment]
Merged: https://github.com/RaspberryPiFoundation/editor-ui/pull/926

**Comment by sra405** [comment]
merged up and any other related tickets will be added separately
