### ISSUE TITLE
[ERROR] Visit design-system-react  0.1.2,  Get 403 Forbidden

### ISSUE THREAD

**Issue by aiminickwong** [RaspberryPiFoundation/editor-ui#695]
USED MASTER REPO AND [v0.19.1], with the same problem.

```
root@7a49234c9a34:~/editor-ui-0.19.1# yarn
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@RaspberryPiFoundation/design-system-react/0.1.2/cc3326c8e0a364ac5baa467ba3a43c249fc69974: Request failed \"403 Forbidden\"".
info If you think this is a bug, please open a bug report with the information provided in "/root/editor-ui-0.19.1/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It seems resource changed, 403...

**Comment by aiminickwong** [comment]
**I had add the .npmrc to root/.npmrc ; and I also had the permisson to login https://npm.pkg.github.com/**
```
[root@btpanel editor-ui-0.19.2]# npm whoami --registry=https://npm.pkg.github.com/
aiminickwong
```

**But I still canot get resource:** **design-system-react**

```
root@btpanel editor-ui-0.19.2]# yarn  install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@RaspberryPiFoundation/design-system-react/0.1.2/cc3326c8e0a364ac5baa467ba3a43c249fc69974: Request failed \"403 Forbidden\"".
info If you think this is a bug, please open a bug report with the information provided in "/www/wwwroot/editor-ui-0.19.2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Is there anyone konws why? @loiswells97

**Comment by sra405** [comment]
> Is there anyone konws why? @loiswells97 @magdalenajadach

Hi @aiminickwong, apologies but we've been developing an in house design system. We incorporated some aspect in our recent HTML/CSS and mobile support releases but currently this is a private package. We're just finalising how to go forwards with this internally so we can unblock community contributors such as yourself. I'm hoping this won't be much longer but I'll post here once I know more 👍

**Comment by aiminickwong** [comment]
@sra405 So that’s it, I’m really looking forward to opening it after the update! :) Thanks.

**Comment by aiminickwong** [comment]
Is there any latest news about this issue? @sra405 Thanks

**Comment by aiminickwong** [comment]
> > 有谁知道为什么？
> 
> 嗨，很抱歉，我们一直在开发一个内部设计系统。我们在最近的 HTML/CSS 和移动支持版本中加入了一些方面，但目前这是一个私有包。我们刚刚敲定如何在内部推进这项工作，以便我们可以解锁像您这样的社区贡献者。我希望这不会太久，但一旦我知道更多👍，我会在这里发帖

Is there any latest news about this issue? Thanks @sra405

**Comment by sra405** [comment]
> > > 有谁知道为什么？
> > 
> > 
> > 嗨，很抱歉，我们一直在开发一个内部设计系统。我们在最近的 HTML/CSS 和移动支持版本中加入了一些方面，但目前这是一个私有包。我们刚刚敲定如何在内部推进这项工作，以便我们可以解锁像您这样的社区贡献者。我希望这不会太久，但一旦我知道更多👍，我会在这里发帖
> 
> Is there any latest news about this issue? Thanks @sra405

Hi @aiminickwong, apologies its taken us so long but the package in `main` should now be public 😄
