### ISSUE TITLE
Allow links to our own domains

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#713]
Currently all links to external sources is blocked however some projects on the Projects Site step users through making links to rpf.io sources. Given we're in complete control of this domain all safeguarding issues should be fine (@MFarringtonRPF to confirm).

### Notes

It should be relatively straightforward to expand [this functionality](https://github.com/RaspberryPiFoundation/editor-ui/blob/main/src/components/Editor/Runners/HtmlRunner/HtmlRunner.jsx#L48C9-L48C21) with the one complexity being a partial match to the domain (ignoring paths).

Keep @pjbRPF informed

**Comment by MFarringtonRPF** [comment]
If we can guarantee 100% control of this domain, agreed I think this is fine.

**Comment by magdalenajadach** [comment]
PR: https://github.com/RaspberryPiFoundation/editor-ui/pull/729
