### ISSUE TITLE
Project instructions components

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#732]
[ADR](https://github.com/RaspberryPiFoundation/documentation/blob/editor-projects-content/docs/codebases/editor/adrs/005-project-site-integration-mvp.md) updated with notes from discovery work.

We need to add the styles to the web component to allow us to render the project instructions inline with [design](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3835-107758&mode=design&t=QL7uMlJyVSuhnWbh-4). Currently github files are parsed through kramdown and stored in projects-admin as HTML strings. Adding styles to the relevant product for the specific classes that are added renders those strings with the required styling.

Component we need to style:

- Code Block
- Code Snippet
- Output Example
- Task
- Call outs
- Collapse

Task list for each component:

- [ ] Identify the current classes added to similar project site projects
- [ ] Determine if these are fit for purpose in this case
- [ ] If not fit for purpose manually add the classnames in the simplified project files in github and remake the project to pass them through to the web component
- [ ] Add the required classes to the web component to style them in line with design
- [ ] Add docs in the editor-ui with a little snippet

### Notes:

- current html and classes passed through from projects site
- adding styles for the existing classnames works for inline styles
- image sizes (i.e. screenshots) need sorting
- check list items and accordions need styles adding
- add docs for each styles with example snippets

**Comment by sra405** [comment]
Note - needs breaking down into individual components & think about aspects that could be done in the design system

**Comment by sra405** [comment]
dependent on https://github.com/RaspberryPiFoundation/editor-ui/issues/741

**Comment by loiswells97** [comment]
Progress Bar done in the Instructions Panel PR but needs styling

**Comment by sra405** [comment]
Notes:

- current html and classes passed through from projects site
- adding styles for the existing classnames works for inline styles
- image sizes (i.e. screenshots) need sorting
- check list items and accordions need styles adding
- add docs for each styles with example snippets

**Comment by sra405** [comment]
used this as a parent ticket and all child have been completed and closed
