### ISSUE TITLE
Un-spaghetti the HtmlRunner 

### ISSUE THREAD

**Issue by magdalenajadach** [RaspberryPiFoundation/editor-ui#733]
The logic around internal/external links is very nested and complicated, it would be nice to take it out to a separate file

Related to: https://github.com/RaspberryPiFoundation/editor-ui/issues/713

**Comment by PetarSimonovic** [comment]
### Tests
Tests need to be updated to capture the current behaviour. 
- [ ] When an external link is loaded, the output tab contains the correct name of the page.
- [ ] After a user has navigated away from an external link, the external link is removed from state (this is happening now, but previously the link persisted in state, which meant that clicking on any other link (external or not) would navigate to the external link again)

**Comment by sra405** [comment]
We need to be able to test what's rendered in the iframe. Ideally this would happen before the render as diving into an iframe with jest is awkward. Consider pulling out `indexPage` and/or `runCode` to make testing the iframes html much easier.
