### ISSUE TITLE
Enable setting sidebar panel function in web-component

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#742]
The current settings panel setup utilises values in cookies to toggle things like the UI font size and light/dark mode. Ensure these values are set and uses in the web component.

Due to the projects site only being in light mode the web component in dark mode might look odd. When the settings tab is included in the web component, get the local storage keys working and toggling the theme and font size, check to see if the dark theme looks out of place and get opinion from @maxelkins. We may need to disable toggling dark mode as a result.

**Comment by maxelkins** [comment]
Defaulting to light mode 👍
