### ISSUE TITLE
Minor copyedit review for the Code Editor UI

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-ui#747]
Minor changes following a copy edit review of the Editor: [CE changes for the Code Editor UI](https://docs.google.com/document/d/1wOXmHQyRNt35d3uIyN6mTL-0x0erzVr6Azu9K3CLkls/edit)

**Comment by loiswells97** [comment]
I'm not sure that changing the pop up message for logged-in users to 'This project will be saved under "Your Projects"' accurately reflects the current functionality, which is that the project only gets remixed (and therefore saved) when the user clicks the save button.
