### ISSUE TITLE
Integration: Instructions pagination styles need finishing

### ISSUE THREAD

**Issue by maxelkins** [RaspberryPiFoundation/editor-ui#839]
Should be clear from the image but a few things to note:

- Disabled button style incorrect
- Progress bar should fill panel
- Progress bar style
- Space between progress bar and buttons
- Padding/Margin around all the elements

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/6ba3ced4-7c31-4c1d-b983-907fa98b3c11)

Expected:

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/ee1737f9-58ad-4014-8011-c873b2eafe61)

Component file: [Figma](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1997-7371&mode=design&t=8pbdq1UkJ1WH0s1p-4)

**Comment by loiswells97** [comment]
@maxelkins, hoping this is fixed now by the miscellaneous bug fixes PR

**Comment by loiswells97** [comment]
Just checked on firefox and looks like it's a little better but still slightly broken
