### ISSUE TITLE
Integration: Output example scrollbar position

### ISSUE THREAD

**Issue by maxelkins** [RaspberryPiFoundation/editor-ui#844]
- Ignore the loss of rounded corners when scroll bar is introduced.

Current:

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/f4dcb644-6ef3-489a-8e7b-5bfb38afc3ca)

Should be:

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/e9656913-3517-4f51-abaa-b6f8dd4c05fc)

**Comment by loiswells97** [comment]
I was assuming this should just wrap rather than scroll @maxelkins
