### ISSUE TITLE
Integration: Code block highlight doesn't fill line

### ISSUE THREAD

**Issue by maxelkins** [RaspberryPiFoundation/editor-ui#847]
![Image](https://github.com/RaspberryPiFoundation/projects-ui/assets/43481548/d596150e-414f-4106-8183-73c76e16ef95)

Expected:

![Image](https://github.com/RaspberryPiFoundation/projects-ui/assets/43481548/ec4d3251-1a8b-4793-9f9c-ebdd0bf6a67e)

**Comment by loiswells97** [comment]
@maxelkins this was a mare but should be fixed with the miscellaneous bugs
