### ISSUE TITLE
Instructions panel does not fill height

### ISSUE THREAD

**Issue by maxelkins** [RaspberryPiFoundation/editor-ui#875]
This means the instructions require you to scroll when the space is available and the steps are not fixed to the bottoms of the panel (scroll bar also not shown here due to this [issue](https://github.com/RaspberryPiFoundation/editor-ui/issues/816))

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/65dbaa08-96cd-4ebb-a9e8-fd2579e63133)

**Comment by sra405** [comment]
closing for now 👍
