### ISSUE TITLE
Fix editor asset URLs

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#910]
This came up in projects support [here](https://raspberrypifoundation.slack.com/archives/C13FSSVDG/p1706276388050649).

So in project [welcome-to-antarctica-step5](https://staging-editor.raspberrypi.org/en/projects/welcome-to-antarctica-step5) there are lots of assets and the URLs weren't correctly populated because `sun.jpg` existed and other assets included `sun.jpg` in the name so someone there's a `contains` match rather than `exact`

**Comment by conorriches** [comment]
Update: tried to replicate by cloning staging database locally then renaming an asset to sun.jpg which should clash with other images in the project, however I couldn't replicate. It seems that editorial have updated the image names before I could start on this, which has made it harder to spot what's going on.

Going to close for now, if we see more of this hopefully we can capture the exact names of all the files so we can replicate locally
