### ISSUE TITLE
Learning Management verification flow feasibility

### ISSUE THREAD

**Issue by danhalson** [RaspberryPiFoundation/editor-ui#942]
@MFarringtonRPF has a [verification flow](https://www.figma.com/file/OTZV5UbWrIYpo59xoOgzsb/DRAFT%3A-LM-verification%2C-onboarding%2C-reset-pass-flows---high-level?type=whiteboard&node-id=156-609&t=K2FLqd1e5CRO3JoN-0) for onboarding schools heavily influenced by CodeClub's. Determine the feasibility.

**Form:**
- Single page form
- Validation
  - check email domains match for owner & head teacher? (potentially against website)
  - possibly checking school against https://find-and-use-an-api.education.gov.uk/ any equivalents for US? (Not MVP)

**Submission:**
- Posts to api endpoint to create school
  -  allow adding class and lesson (not students) before verification
  -  means we need `owner_id` stored against the school

**Verification:**
- Management options:
  - Administrate
    - Likely needs to exist regardless of verification process
    - Control over ui, provide a 'verify' button
    - Needs transactional email (details below)
    - Easy to glom onto events for email
    - Familiar, and quick to set-up
  - ~~Salesforce~~
    - ~~SalesforceConnect _could_ allow us to avoid syncing, see [clubs-api implementation](https://github.com/RaspberryPiFoundation/clubs-api/blob/main/app/models/club_role.rb) or at the very least allows us to be atomic in our updates.~~
    - ~~Salesforce provides email capabilities~~
    - ~~Would need to either make Salesforce readonly and still implement administrate for editing pre verification, only allow editing via Salesforce, or a two way sync~~
      - ~~This is more error prone~~
    - ~~Salesforce is very tricky when it comes to validation, so data tends to get dirty easily~~

**Post verification:**
- Email users
- Call to profile to set up organisation (and roles)

**Notes / Questions:**

- ~~Is there a wider business need to involve Salesforce, and is this likely to become a requirement?~~
- Look into email options
  - Having transactional email support will probably be beneficial in the long run anyway
  - ~~Creating a dependency on Salesforce for just email, may be a bigger burden in the long run~~
  - Possibilities
    - ~~ActiveMailer~~
    - ~~Mandrill~~
    - [Sendgrid](https://docs.sendgrid.com/for-developers/sending-email/rubyonrails) (worth talking to clubs team about their Sendgrid experience)

**Comment by danhalson** [comment]
Implement Administrate on editor-api (expectation is no need for Salesforce)
- School dashboard
  - Verify button

**Comment by danhalson** [comment]
Implement [Sendgrid](https://docs.sendgrid.com/for-developers/sending-email/rubyonrails) on editor-api
- Add hook and template email on school application
- Add hooks and template emails on verification
- check for other hooks...pre verification?

**Comment by danhalson** [comment]
Changes on editor-api

- Allow adding class and lesson (not students) before verification

**Comment by sra405** [comment]
>   * check email domains match for owner & head teacher
>   * another way of verifying schools (i.e https://find-and-use-an-api.education.gov.uk) if 

We're not doing any form of domain locking organisations/schools for MVP

**Comment by sra405** [comment]
> * Allow adding class and lesson (not students) before verification

I think this functionality exists in https://github.com/RaspberryPiFoundation/editor-api/issues/239 but probably isn't MVP now. As long as what we have won't cause us issues I'm open to how we do this on the backend 👍

**Comment by sra405** [comment]
Looks good to me and I've made tickets off the back of this 👍 closing
