### ISSUE TITLE
Reference ticket: LM Design system components

### ISSUE THREAD

**Issue by maxelkins** [RaspberryPiFoundation/editor-ui#960]
# Learning management - Design system components

Component we will be using in Learning managment and would be nice to have add to the design system, in the process.

## Components

Key:
✅ = Available
❌ = Not available
🟠 = Yes, but not using design system
🛠️ = WIP / Needs attention
❓ = Not sure

| Component                                          | Design | Core | React | Editor |
| -------------------------------------------------- | :----: | :--: | :---: | :----: |
| Colour variables                                   |   ✅    |  ✅   |   -   |  🛠️   |
| Text variables                                     |   ✅    |  ✅   |   -   |  🛠️   |
| Spacing variables                                  |   ✅    |  ✅   |   -   |  🛠️   |
| Button                                             |   ✅    |  ✅   |   ✅   |   🟠   |
| Input (Text)                                       |   ✅    |  ✅   |   ✅   |   🟠   |
| Input (Select)                                     |   ✅    |  ✅   |   ✅   |   ❓   |
| Input (Radio)                                      |   ✅    |  ✅   |   ❌   |   ❓    |
| Input (Check)                                      |   ✅    |  ✅   |   ✅   |   ❓    |
| Input (Search)                                     |   ❌    |  ❌   |   ❌   |   ❌    |
| Input (Toggle)                                     |  🛠️   |  ❌   |   ❌   |   ❌    |
| Input (Select button)<br>aka check/radio alt style |   ✅    |  ❌   |   ❌   |   🟠   |
| Modal                                              |   ✅    |  ❌   |   ❌   |   🟠   |
| Form progress indicator                            |  ✅   |  ✅   |   ✅   |   ❌    |
| Alert                                              |   ✅    |  ✅   |   ✅   |   ❌    |
| Accordion                                          |   ✅    |  ✅   |   ✅   |   ❌    |
| Icons                                              |  🛠️   | 🛠️  |  🛠️  |  🛠️   |
| Menu dropdowns                                     |   ✅    |  ❌   |   ❌   |  🛠️   |
| Pill/Tag                                           |   ✅    |  ❌   |   ❌   |   ❌    |
| Breadcrumb                                         |   ✅    |  ❌   |   ❌   |   ❌    |
## Further details

Colour, text, spacing variables:
- Ready to use, editor currently using a mix of local and design system variables/styles.

Button:
- Ready to use, partially implemented in editor.

Input (Text/select/radio/checkbox):
- Needs implementing in react, some local style in editor.

Input (Select button):
- Design complete and currently implemented in editor but not in design system.

Modal:
- Design complete, a variation of which is implemented in the editor.

Icons:
- We have access to the material design icons in the design system but it currently relies on an icon font. Need to access if there is a better way of doing this, and if we can ensure accessibility with this method. ([Issue](https://github.com/RaspberryPiFoundation/design-system-core/issues/39))

**Comment by sra405** [comment]
High priority components:

- Input text - currently ongoing PR
- Input select
- Input check
- Form progress indicator
- Accordion

Lower priority

- Input search

Questions - what are these @maxelkins??

- Input Select button?
- Alert

**Comment by sra405** [comment]
Questions - what are these @maxelkins??

Input Select button?
Alert

**Comment by sra405** [comment]
separated out required components for this sprint so pushing this back to next sprint for reprioritisation

**Comment by sra405** [comment]
to review in backlog, update and see if anything else is needed

**Comment by sra405** [comment]
discussed in backlog and no additional design system components needed for this sprint 👍

**Comment by sra405** [comment]
to be discussed:
- Input search (for adding students to classes)
- menu dropdowns
- breadcrumb
