### ISSUE TITLE
Theme glitch when switching dark/light modes

### ISSUE THREAD

**Issue by magdalenajadach** [RaspberryPiFoundation/editor-ui#970]
Issue happening on main, but not on Prod

When switching between dark/light modes for Editor and WC - weird styles are being applied. Getting fixed after a reload.

Screens attached

<img width="1537" alt="Screenshot 2024-03-14 at 11 32 01" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/8046557/38167260-7b74-49c4-93d4-9c0fe8f0fe04">
<img width="1557" alt="Screenshot 2024-03-14 at 11 32 09" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/8046557/5613364e-33cf-4053-9cb5-896abf24fcff">
<img width="1595" alt="Screenshot 2024-03-14 at 11 32 24" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/8046557/14a965bc-cc58-4725-bf57-8cfd5a852cee">

<img width="1538" alt="Screenshot 2024-03-14 at 11 32 39" src="https://github.com/RaspberryPiFoundation/editor-ui/assets/8046557/8661482c-5034-456b-a3ff-f7ead491b615">

**Comment by sra405** [comment]
done as part of #919
