### ISSUE TITLE
Edit project name in web component

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#986]
Given we want to use the web component in editor-standalone and switch editor.raspberrypi.org traffic over to that repo we need to ensure the existing functionality is supported in the web component. One aspect that needs including is the ability to edit a projects name in the web component.

[Slack thread](https://raspberrypifoundation.slack.com/archives/C02JBAA2NFP/p1713352569352239)

### Notes

- Some web component integrations need the existing read-only project name functionality (i.e the [projects site integration](https://projects.raspberrypi.org/en/projects/editor-hello-world/editor))
- Consider toggling this functionality using an attribute to `editor-wc`

**Comment by floehopper** [comment]
It's worth noting that it is already possible to rename a project on the "My projects" page; just not in the project bar of the editor web component.

**Comment by floehopper** [comment]
Hopefully addressed in https://github.com/RaspberryPiFoundation/editor-ui/pull/1009 & https://github.com/RaspberryPiFoundation/editor-standalone/pull/125.

**Comment by MFarringtonRPF** [comment]
@danhalson can this be marked as closed given comments above? Looks to be added as well in the temp branch.

**Comment by MFarringtonRPF** [comment]
Unclear if still needed.

**Comment by floehopper** [comment]
@MFarringtonRPF I'm pretty sure it's OK to close this - the changes I made in those two PRs mentioned above allow users to rename a project by clicking on the project name in editor-standalone.
